import { WarehouseItem } from "./types";

export const INITIAL_WAREHOUSE_ITEMS: WarehouseItem[] = [
  // 1. STAMPA OFFSET & DIGITALE
  {
    id: "resta-pap-001",
    code: "PAT-OP-130-70100",
    name: "Patinata Opaca 130g 70x100",
    category: "offset_digitale",
    subcategory: "Patinata Opaca",
    unit: "pacchi (250ff)",
    quantity: 12,
    minStockAlert: 8,
    optimalStock: 25,
    supplier: "Burgo Distribuzione",
    location: "Corsia Carta - Bancale 01",
    unitCost: 32.5,
    notes: "Ideale per volantini, flyer e interni cataloghi commerciali.",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "resta-pap-002",
    code: "PAT-OP-170-70100",
    name: "Patinata Opaca 170g 70x100",
    category: "offset_digitale",
    subcategory: "Patinata Opaca",
    unit: "pacchi (250ff)",
    quantity: 3, // SOTTOSCORTA CRITICO!
    minStockAlert: 6,
    optimalStock: 20,
    supplier: "Burgo Distribuzione",
    location: "Corsia Carta - Bancale 02",
    unitCost: 41.2,
    notes: "Carta per pieghevoli di qualità e depliant.",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "resta-pap-003",
    code: "PAT-OP-300-70100",
    name: "Patinata Opaca 300g 70x100",
    category: "offset_digitale",
    subcategory: "Patinata Opaca",
    unit: "pacchi (125ff)",
    quantity: 5, // ATTENZIONE
    minStockAlert: 5,
    optimalStock: 18,
    supplier: "Fedrigoni",
    location: "Corsia Carta - Bancale 03",
    unitCost: 38.0,
    notes: "Cartoncino per cartelline, copertine e cartoline.",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "resta-pap-004",
    code: "PAT-LUC-150-70100",
    name: "Patinata Lucida 150g 70x100",
    category: "offset_digitale",
    subcategory: "Patinata Lucida",
    unit: "pacchi (250ff)",
    quantity: 15,
    minStockAlert: 6,
    optimalStock: 20,
    supplier: "Burgo Distribuzione",
    location: "Corsia Carta - Bancale 04",
    unitCost: 36.8,
    notes: "Grande resa di brillantezza per immagini e cataloghi moda/food.",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "resta-pap-005",
    code: "USO-BIA-80-6488",
    name: "Usomano Bianca Naturale 80g 64x88",
    category: "offset_digitale",
    subcategory: "Usomano",
    unit: "pacchi (500ff)",
    quantity: 18,
    minStockAlert: 10,
    optimalStock: 35,
    supplier: "Fedrigoni",
    location: "Corsia Carta - Bancale 05",
    unitCost: 28.0,
    notes: "Per carta da lettere, modulistica e dispense.",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "resta-pap-006",
    code: "USO-BIA-120-6488",
    name: "Usomano Bianca Naturale 120g 64x88",
    category: "offset_digitale",
    subcategory: "Usomano",
    unit: "pacchi (250ff)",
    quantity: 7,
    minStockAlert: 5,
    optimalStock: 15,
    supplier: "Fedrigoni",
    location: "Corsia Carta - Bancale 06",
    unitCost: 24.5,
    notes: "Ottima mano per buste e coordinati.",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "resta-pap-007",
    code: "DIG-SRA3-170-OP",
    name: "SRA3 Patinata Opaca 170g Digitale",
    category: "offset_digitale",
    subcategory: "Digitale SRA3",
    unit: "scatole (500ff)",
    quantity: 8,
    minStockAlert: 4,
    optimalStock: 12,
    supplier: "Antalis",
    location: "Scaffale Digitale A1",
    unitCost: 22.0,
    notes: "Fogli per la macchina da stampa digitale a foglio rapida.",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "resta-pap-008",
    code: "DIG-SRA3-300-OP",
    name: "SRA3 Patinata Opaca 300g Digitale",
    category: "offset_digitale",
    subcategory: "Digitale SRA3",
    unit: "scatole (250ff)",
    quantity: 2, // SOTTOSCORTA CRITICO!
    minStockAlert: 4,
    optimalStock: 10,
    supplier: "Antalis",
    location: "Scaffale Digitale A2",
    unitCost: 25.0,
    notes: "Supporto base per biglietti da visita digitali express e copertine.",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "resta-pap-009",
    code: "CHIM-CB-BIA-4361",
    name: "Carta Chimica CB Bianca 56g 43x61",
    category: "offset_digitale",
    subcategory: "Carta Autocopiante",
    unit: "pacchi (500ff)",
    quantity: 6,
    minStockAlert: 4,
    optimalStock: 12,
    supplier: "Torraspapel / Lecta",
    location: "Corsia B - Scaffale 1",
    unitCost: 19.5,
    notes: "Primo foglio per blocchi ricalco fatture e ddt.",
    lastUpdated: new Date().toISOString(),
  },

  // 2. EDITORIA & LEGATORIA
  {
    id: "resta-ed-001",
    code: "LEG-PUR-2KG",
    name: "Colla PUR Poliuretanica per Brossura",
    category: "editoria_legatoria",
    subcategory: "Collanti",
    unit: "cartucce (2kg)",
    quantity: 2, // ATTENZIONE
    minStockAlert: 2,
    optimalStock: 6,
    supplier: "Planatol",
    location: "Armadio Collanti Legatoria",
    unitCost: 45.0,
    notes: "Indispensabile per libri d'arte, monografie e carte patinate pesanti.",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "resta-ed-002",
    code: "LEG-HOTMELT-25KG",
    name: "Colla Hot-Melt Brossura EVA Standard",
    category: "editoria_legatoria",
    subcategory: "Collanti",
    unit: "sacchi (25kg)",
    quantity: 4,
    minStockAlert: 2,
    optimalStock: 8,
    supplier: "Planatol",
    location: "Reparto Confezione",
    unitCost: 85.0,
    notes: "Per tesi di laurea, opuscoli e brossura economica.",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "resta-ed-003",
    code: "PLAST-BOB-SOFT-330",
    name: "Bobina Plastificazione Soft-Touch 330mm x 500m",
    category: "editoria_legatoria",
    subcategory: "Plastificazione",
    unit: "rotoli",
    quantity: 1, // SOTTOSCORTA CRITICO!
    minStockAlert: 2,
    optimalStock: 5,
    supplier: "MagData",
    location: "Macchina Plastificatrice",
    unitCost: 65.0,
    notes: "Effetto vellutato per copertine di prestigio e cataloghi di lusso.",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "resta-ed-004",
    code: "PLAST-BOB-OPA-330",
    name: "Bobina Plastificazione Opaca Termica 330mm x 1000m",
    category: "editoria_legatoria",
    subcategory: "Plastificazione",
    unit: "rotoli",
    quantity: 4,
    minStockAlert: 2,
    optimalStock: 6,
    supplier: "MagData",
    location: "Macchina Plastificatrice",
    unitCost: 52.0,
    notes: "Finitura opaca antiriflesso standard.",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "resta-ed-005",
    code: "LEG-FILO-REFE-30",
    name: "Filo Refe Poliestere n.30 per Cucitura",
    category: "editoria_legatoria",
    subcategory: "Filo Refe",
    unit: "rocchetti (5000m)",
    quantity: 3,
    minStockAlert: 1,
    optimalStock: 4,
    supplier: "Amann Group",
    location: "Cucitrice a Filo Refe",
    unitCost: 28.0,
    notes: "Per libri cuciti ad alta resistenza.",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "resta-ed-006",
    code: "CART-GRIGIO-20",
    name: "Cartone Grigio Legatoria 2.0mm 70x100",
    category: "editoria_legatoria",
    subcategory: "Cartonaggio",
    unit: "fogli stesi",
    quantity: 45,
    minStockAlert: 20,
    optimalStock: 100,
    supplier: "Burgo",
    location: "Scaffale Cartonaggio",
    unitCost: 1.8,
    notes: "Per copertine rigide cartonate e tesi con frontespizio in tela.",
    lastUpdated: new Date().toISOString(),
  },

  // 3. IMMAGINE COORDINATA & FOIL NOBILITAZIONI
  {
    id: "resta-coo-001",
    code: "FED-TINT-GESSO-250",
    name: "Fedrigoni Tintoretto Gesso 250g 72x102",
    category: "immagine_coordinata",
    subcategory: "Carte Pregiate",
    unit: "pacchi (100ff)",
    quantity: 6,
    minStockAlert: 3,
    optimalStock: 12,
    supplier: "Fedrigoni",
    location: "Reparto Carte Speciali",
    unitCost: 49.0,
    notes: "Carta marcata a feltro prestigiosa per partecipazioni e biglietti da visita.",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "resta-coo-002",
    code: "FED-ACQ-AVOR-240",
    name: "Fedrigoni Acquerello Avorio 240g 72x102",
    category: "immagine_coordinata",
    subcategory: "Carte Pregiate",
    unit: "pacchi (100ff)",
    quantity: 2, // ATTENZIONE
    minStockAlert: 2,
    optimalStock: 8,
    supplier: "Fedrigoni",
    location: "Reparto Carte Speciali",
    unitCost: 52.0,
    notes: "Texture vergata classica di altissima eleganza.",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "resta-coo-003",
    code: "BUST-1123-STRIP",
    name: "Buste Intestate 11x23 cm con Strip (senza finestra)",
    category: "immagine_coordinata",
    subcategory: "Buste",
    unit: "scatole (500pz)",
    quantity: 9,
    minStockAlert: 4,
    optimalStock: 20,
    supplier: "Pigna / Blasetti",
    location: "Scaffale Buste Reparto B",
    unitCost: 26.5,
    notes: "Formato standard commerciale con patella autoadesiva.",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "resta-coo-004",
    code: "FOIL-CALDO-ORO-120",
    name: "Bobina Foil Stampa a Caldo Oro Lucido 120mm x 122m",
    category: "immagine_coordinata",
    subcategory: "Nobilitazione Stampa a Caldo",
    unit: "rotoli",
    quantity: 4,
    minStockAlert: 2,
    optimalStock: 8,
    supplier: "Kurz Foil",
    location: "Armadio Platina Stampa a Caldo",
    unitCost: 38.0,
    notes: "Per nobilitazione dorata su biglietti da visita e partecipazioni.",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "resta-coo-005",
    code: "FOIL-CALDO-ARG-120",
    name: "Bobina Foil Stampa a Caldo Argento Lucido 120mm x 122m",
    category: "immagine_coordinata",
    subcategory: "Nobilitazione Stampa a Caldo",
    unit: "rotoli",
    quantity: 1, // SOTTOSCORTA CRITICO!
    minStockAlert: 2,
    optimalStock: 6,
    supplier: "Kurz Foil",
    location: "Armadio Platina Stampa a Caldo",
    unitCost: 38.0,
    notes: "Foil argento brillante ad alta adesione.",
    lastUpdated: new Date().toISOString(),
  },

  // 4. PARTECIPAZIONI & CERIMONIE
  {
    id: "resta-cer-001",
    code: "AMALFI-1530-COT",
    name: "Carta a Mano d'Amalfi 100% Cotone 200g (Bordi Intonsi)",
    category: "cerimonie",
    subcategory: "Carta a Mano d'Amalfi",
    unit: "fogli singoli",
    quantity: 80, // ATTENZIONE (matrimonio tipico richiede 100-150 pz)
    minStockAlert: 100,
    optimalStock: 300,
    supplier: "Cartiera Amatruda Amalfi",
    location: "Cassetto Progetti Nozze",
    unitCost: 1.45,
    notes: "Il top di gamma per le partecipazioni nozze a Bari. Bordi sfilacciati naturali.",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "resta-cer-002",
    code: "AMALFI-BUST-1122",
    name: "Buste Amalfi Coordinate 11x22 cm con lembo a punta",
    category: "cerimonie",
    subcategory: "Carta a Mano d'Amalfi",
    unit: "pezzi",
    quantity: 95,
    minStockAlert: 100,
    optimalStock: 300,
    supplier: "Cartiera Amatruda Amalfi",
    location: "Cassetto Progetti Nozze",
    unitCost: 1.1,
    notes: "Chiusura nozze per partecipazioni Amalfi.",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "resta-cer-003",
    code: "CERALACCA-BORG",
    name: "Stecche Ceralacca Flessibile Rosso Borgogna",
    category: "cerimonie",
    subcategory: "Sigilli Ceralacca",
    unit: "stecche",
    quantity: 14,
    minStockAlert: 5,
    optimalStock: 25,
    supplier: "Bortoletti",
    location: "Tavolo Cerimonie",
    unitCost: 2.2,
    notes: "Non si spezza durante la spedizione postale. Resa ca. 10 sigilli a stecca.",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "resta-cer-004",
    code: "CERALACCA-ORO",
    name: "Stecche Ceralacca Flessibile Oro Antico Metallizzato",
    category: "cerimonie",
    subcategory: "Sigilli Ceralacca",
    unit: "stecche",
    quantity: 3, // SOTTOSCORTA CRITICO!
    minStockAlert: 6,
    optimalStock: 20,
    supplier: "Bortoletti",
    location: "Tavolo Cerimonie",
    unitCost: 2.5,
    notes: "Molto richiesta per sigilli monogramma sposi.",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "resta-cer-005",
    code: "NASTRO-ORG-CIPRIA",
    name: "Nastro in Organza Cipria Bordata 20mm x 50m",
    category: "cerimonie",
    subcategory: "Nastri Decorativi",
    unit: "bobine",
    quantity: 2,
    minStockAlert: 2,
    optimalStock: 6,
    supplier: "Nastrificio Italiano",
    location: "Tavolo Cerimonie",
    unitCost: 12.0,
    notes: "Per legatura booklet messa e partecipazioni coordinate.",
    lastUpdated: new Date().toISOString(),
  },

  // 5. STAMPA SU INDUMENTI (DTF & SERIGRAFIA)
  {
    id: "resta-dtf-001",
    code: "TSH-COT-NER-M",
    name: "T-Shirt Neutra 100% Cotone 155g Nera - Taglia M",
    category: "dtf_abbigliamento",
    subcategory: "T-Shirt Neutre",
    unit: "pezzi",
    quantity: 35,
    minStockAlert: 20,
    optimalStock: 80,
    supplier: "2Stamp / JHK",
    location: "Scaffale Capi Neutri - Ripiano 2",
    unitCost: 2.1,
    notes: "T-shirt basic ring-spun per stampa transfer DTF.",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "resta-dtf-002",
    code: "TSH-COT-NER-L",
    name: "T-Shirt Neutra 100% Cotone 155g Nera - Taglia L",
    category: "dtf_abbigliamento",
    subcategory: "T-Shirt Neutre",
    unit: "pezzi",
    quantity: 12, // ATTENZIONE
    minStockAlert: 20,
    optimalStock: 80,
    supplier: "2Stamp / JHK",
    location: "Scaffale Capi Neutri - Ripiano 2",
    unitCost: 2.1,
    notes: "La taglia più richiesta per forniture aziendali.",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "resta-dtf-003",
    code: "TSH-COT-NER-XL",
    name: "T-Shirt Neutra 100% Cotone 155g Nera - Taglia XL",
    category: "dtf_abbigliamento",
    subcategory: "T-Shirt Neutre",
    unit: "pezzi",
    quantity: 4, // SOTTOSCORTA CRITICO!
    minStockAlert: 15,
    optimalStock: 50,
    supplier: "2Stamp / JHK",
    location: "Scaffale Capi Neutri - Ripiano 2",
    unitCost: 2.2,
    notes: "Scorta minima insufficiente per commesse veloci.",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "resta-dtf-004",
    code: "TSH-COT-BIA-L",
    name: "T-Shirt Neutra 100% Cotone 155g Bianca - Taglia L",
    category: "dtf_abbigliamento",
    subcategory: "T-Shirt Neutre",
    unit: "pezzi",
    quantity: 40,
    minStockAlert: 15,
    optimalStock: 60,
    supplier: "2Stamp / JHK",
    location: "Scaffale Capi Neutri - Ripiano 1",
    unitCost: 1.95,
    notes: "Base bianca ottima per loghi colorati.",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "resta-dtf-005",
    code: "CAP-BASEBALL-NER",
    name: "Cappellino 5 Pannelli con Visiera Neutro Nero",
    category: "dtf_abbigliamento",
    subcategory: "Accessori Neutri",
    unit: "pezzi",
    quantity: 18,
    minStockAlert: 10,
    optimalStock: 40,
    supplier: "Atlantis Headwear",
    location: "Scaffale Capi Neutri - Ripiano 4",
    unitCost: 2.8,
    notes: "Chiusura regolabile in velcro, perfetto per transfer DTF su termopressa a tazza/berretto.",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "resta-dtf-006",
    code: "DTF-FILM-BOB-60",
    name: "Bobina Film DTF Cold Peel 60cm x 100m",
    category: "dtf_abbigliamento",
    subcategory: "Consumabili DTF",
    unit: "rotoli",
    quantity: 2,
    minStockAlert: 1,
    optimalStock: 4,
    supplier: "Plotterfilms",
    location: "Reparto Stampante DTF",
    unitCost: 95.0,
    notes: "Film per stampante industriale DTF a nastro.",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "resta-dtf-007",
    code: "DTF-POLV-HOTMELT-1K",
    name: "Polvere Termofusibile DTF Bianca Poliuretanica (1 Kg)",
    category: "dtf_abbigliamento",
    subcategory: "Consumabili DTF",
    unit: "sacchi (1kg)",
    quantity: 3,
    minStockAlert: 2,
    optimalStock: 6,
    supplier: "Plotterfilms",
    location: "Reparto Stampante DTF",
    unitCost: 24.0,
    notes: "Polvere per forno di asciugatura DTF con ottima elasticità.",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "resta-dtf-008",
    code: "DTF-INK-WH-1000",
    name: "Inchiostro DTF Textile Bianco Alta Coprenza (1000ml)",
    category: "dtf_abbigliamento",
    subcategory: "Inchiostri DTF",
    unit: "flaconi (1000ml)",
    quantity: 1, // SOTTOSCORTA CRITICO! Il bianco si consuma doppio!
    minStockAlert: 3,
    optimalStock: 6,
    supplier: "DuPont / Artistri",
    location: "Armadio Inchiostri DTF",
    unitCost: 58.0,
    notes: "Consumo elevato per il fondo bianco su magliette nere e scure.",
    lastUpdated: new Date().toISOString(),
  },

  // 6. ALLESTIMENTI, INSEGNE & VETROFANIE
  {
    id: "resta-all-001",
    code: "VIN-SABB-DUST-122",
    name: "Bobina Vinile Sabbiato Dusted Crystal 122cm x 50m",
    category: "allestimenti_vetrofanie",
    subcategory: "Pellicole Vetrofanie",
    unit: "rotoli",
    quantity: 1, // ATTENZIONE
    minStockAlert: 1,
    optimalStock: 3,
    supplier: "APA / Guandong",
    location: "Porta-Bobine Plotter",
    unitCost: 145.0,
    notes: "Effetto vetro satinato per sabbiatura vetrine negozi e partizioni uffici a Bari.",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "resta-all-002",
    code: "VIN-ADES-POL-137",
    name: "Bobina Vinile Polimerico Bianco Lucido 137cm x 50m",
    category: "allestimenti_vetrofanie",
    subcategory: "Vinile da Stampa",
    unit: "rotoli",
    quantity: 2,
    minStockAlert: 1,
    optimalStock: 4,
    supplier: "Ritrama / Fedrigoni Self-Adhesives",
    location: "Porta-Bobine Plotter",
    unitCost: 118.0,
    notes: "Per adesivi automezzi (auto e furgoni commerciali) a lunga durata.",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "resta-all-003",
    code: "ROLLUP-STRUTT-85",
    name: "Struttura Roll-Up Avvolgibile in Alluminio 85x200cm",
    category: "allestimenti_vetrofanie",
    subcategory: "Espositori Stand",
    unit: "pezzi",
    quantity: 7,
    minStockAlert: 4,
    optimalStock: 15,
    supplier: "Showdown Displays",
    location: "Ripiano Espositori Allestimento",
    unitCost: 14.5,
    notes: "Include sacca di trasporto imbottita. Il best-seller per convegni ed eventi.",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "resta-all-004",
    code: "BANNER-PVC-510-106",
    name: "Bobina Banner Telone PVC Frontlit 510g 106cm x 50m",
    category: "allestimenti_vetrofanie",
    subcategory: "Striscioni Pubblicitari",
    unit: "rotoli",
    quantity: 2,
    minStockAlert: 1,
    optimalStock: 3,
    supplier: "Guandong",
    location: "Porta-Bobine Plotter",
    unitCost: 78.0,
    notes: "Per striscioni da esterno occhiellati.",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "resta-all-005",
    code: "FOREX-BIA-3MM-2030",
    name: "Lastra Forex PVC Espanso Bianco 3mm 200x300cm",
    category: "allestimenti_vetrofanie",
    subcategory: "Pannelli Rigidi",
    unit: "lastre",
    quantity: 5,
    minStockAlert: 3,
    optimalStock: 12,
    supplier: "3A Composites",
    location: "Rastrelliera Lastre Grandi",
    unitCost: 29.0,
    notes: "Per insegne interne, cartellonistica e pannelli sagomati a fresa.",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "resta-all-006",
    code: "PLEXI-TRAS-4MM-2030",
    name: "Lastra Plexiglass Trasparente Colato 4mm 205x305cm",
    category: "allestimenti_vetrofanie",
    subcategory: "Pannelli Rigidi",
    unit: "lastre",
    quantity: 2,
    minStockAlert: 2,
    optimalStock: 5,
    supplier: "Polycasa",
    location: "Rastrelliera Lastre Grandi",
    unitCost: 110.0,
    notes: "Per targhe professionali da esterno con distanziali in acciaio inox.",
    lastUpdated: new Date().toISOString(),
  },

  // 7. CONSUMABILI TECNICI & INCHIOSTRI OFFSET/DIGITALE
  {
    id: "resta-tec-001",
    code: "CTP-LASTRE-745605",
    name: "Lastre CTP Termiche 0.30mm 745x605mm (Offset 70x100)",
    category: "consumabili_tecnici",
    subcategory: "Lastre Offset",
    unit: "confezioni (50pz)",
    quantity: 2, // ATTENZIONE
    minStockAlert: 2,
    optimalStock: 6,
    supplier: "Agfa Graphics",
    location: "Camera Oscura / CTP",
    unitCost: 175.0,
    notes: "Lastre termiche senza sviluppo chimico per macchina offset 4 colori.",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "resta-tec-002",
    code: "INK-OFF-CYAN-25",
    name: "Inchiostro Offset Quickset Cyan Process (2.5 Kg)",
    category: "consumabili_tecnici",
    subcategory: "Inchiostri Offset",
    unit: "barattoli (2.5kg)",
    quantity: 3,
    minStockAlert: 2,
    optimalStock: 6,
    supplier: "Hubergroup",
    location: "Armadio Inchiostri Macchina Offset",
    unitCost: 32.0,
    notes: "Inchiostro vegetale rapida essiccazione per quadricromia.",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "resta-tec-003",
    code: "INK-OFF-MAG-25",
    name: "Inchiostro Offset Quickset Magenta Process (2.5 Kg)",
    category: "consumabili_tecnici",
    subcategory: "Inchiostri Offset",
    unit: "barattoli (2.5kg)",
    quantity: 1, // SOTTOSCORTA CRITICO!
    minStockAlert: 2,
    optimalStock: 6,
    supplier: "Hubergroup",
    location: "Armadio Inchiostri Macchina Offset",
    unitCost: 34.0,
    notes: "Inchiostro magenta di base, urgente riordino.",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "resta-tec-004",
    code: "TONER-DIG-BLACK-HI",
    name: "Cartuccia Toner Nero Digitale Alta Capacità",
    category: "consumabili_tecnici",
    subcategory: "Toner Macchina Digitale",
    unit: "cartucce",
    quantity: 2,
    minStockAlert: 1,
    optimalStock: 4,
    supplier: "Ricoh / Xerox",
    location: "Mobiletto Stampante Digitale",
    unitCost: 85.0,
    notes: "Resa ca. 45.000 copie A4 al 5% di copertura.",
    lastUpdated: new Date().toISOString(),
  },
];
